language: node_js
node_js:
  - "10"
jobs:
  include:
    - script: npm install
    - script: npm run build
    - script: npm run build && npm run coverage
      deploy:
        - provider: pages
          skip_cleanup: true
          token: $GITHUB_OAUTH_TOKEN
          local_dir: ./dist
          keep_history: true
          edge: true
          on:
            tags: false
        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file:
            - "./dist/build/table-pager.js"
            - "./dist/build/table-pager.mjs"
            - "./dist/build/table-pager.css"
          skip_cleanup: true
          on:
            tags: true
